import { graphql, useStaticQuery } from "gatsby";

const useSiteMetadata = (): Queries.SiteMetaTitleQuery => {
  // https://www.gatsbyjs.com/docs/how-to/local-development/graphql-typegen/#using-the-autogenerated-queries-types
  return useStaticQuery(graphql`
    query SiteMetaTitle {
      site {
        siteMetadata {
          title
        }
      }
    }
  `);
};

export default useSiteMetadata;
