import { PageProps, graphql, useStaticQuery } from "gatsby";

const useSiteMetadata = () => {
  // https://www.gatsbyjs.com/docs/how-to/local-development/graphql-typegen/#using-the-autogenerated-queries-types
  const response: PageProps<Queries.SiteMetaTitleQuery> = useStaticQuery(
    graphql`
      query SiteMetaTitle {
        site {
          siteMetadata {
            title
          }
        }
      }
    `,
  );
  // HACK: response.data is maybe undefined.
  return response.data?.site?.siteMetadata;
};

export default useSiteMetadata;
